[package]
name = "rusty_json"
version = "1.0.0"
edition = "2021"
authors = ["Ammar Dev"]
description = "A simple library/crate to create and read and write json"
repository = "https://github.com/ammardevz/rusty_json"
license = "MIT"


[dependencies]
lazy_static = "1.4.0"
jsonparser = "0.2.1"
quote = "1.0.36"
syn = "2.0.66"
